source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 2.5'
pod 'Mantle', '~> 1.5'
pod 'ReactiveCocoa', '~> 2.4.4'
pod 'Masonry', '~> 0.6.0'
pod 'DateTools'
pod 'SDWebImage', '~> 3.7.1'
pod 'NYSegmentedControl'